#+TITLE: README
#+AUTHOR: Charles-Édouard Lizott
#+date: 7 octobre 2023

** Introduction
Dans ce répertoire /git/, on retrouve toutes les sous-routines Fortran 90 nécessaires à la compilation d'une version /MPI/ de Wavewatch III couplée avec notre modèle /shallow water/ multicouche.
Bien qu'un couplage entre Wavewatch III et un autre modèle soit réalisable avec le module OASIS, j'ai tout simplement modifier trois sous-routines du modèle pour le coupler avec le miens.
Cette méthode est bien plus simple et permet d'avoir un plus grand contrôle sur le couplage.

** Arborescence des fichiers et sous-routines
*** Python-Build-Fonctions
Contient toutes les scripts Python nécessaires créant les forçage pris en compte par /Wavewatch III/. 

**** build grid.py
Crée le fichier /mapsta.inp/ et /bottom.inp/
Le fichier texte /mapsta.inp/ décrit le type de point sur la grille utilisée par Wavewatch.
Par exemple : mer, glace, côte, etc. 
Le fichier texte /bottom.inp/ décrit la profondeur sur tous les points.

**** build_currents.py
Crée un fichier netCDF contenant les courants à envoyer à /Wavewatch III/, soit *WW3Currentforcings.nc*.

**** build winds.py
Crée un fichier netCDF contenant les vents à envoyer à /Wavewatch III/, soit *WW3Windforcings.nc*.

*** ww3 modified subroutines
Contient les sous-routines de type /.f90/ qui ont été modifiées pour faire fonctionner Wavewatch en coupage avec le modèle /shallow water/.
il faut donc remplacer les mêmes routines du dossier /wavewatch/ftn/ et recompiler /Wavewatch/ en mode MPI pour que ça fonctionne.

*** ww3 inp files
Ce dossier contient tous les scripts d'input de /Wavewatch/ (les fichiers de type /.inp/).
Ces derniers décrivent le comportement du modèle, comme la taille du domaine, les date de début et fin, le pas de temps, etc.
C'est par eux qu'on informe le modèle du comment on veut qu'il fonctionne.
En ordre, les plus importants : 
+ /ww3-grid.inp/;
+ /ww3-strt.inp/;
+ /ww3_prnc.inp/;
+ /prnc_cur.inp/;
+ /prnc_wnd.inp/;
+ /ww3_shel.inp/.

*** beluga workcase
Dossier à copier pour lancer une /run/ sur l'ordinateur /beluga/ /computecanada.ca/.

*** oxygen workcase
Dossier à copier pour lancer une /run/ sur l'ordinateur /Oxygen/. 
